### ISSUE TITLE
171211 종설1 최종 발표 준비

### ISSUE THREAD

**Issue by hyunjun529** [CSID-DGU/2017-2-CECD-Tres-5#8]
각각의 기능 테스트를 동영상으로 시연한다.

- [x] 마커 
- [x] ARKit 예제
- [x] 앵커 제어

**Comment by hyunjun529** [comment]
Objective C++에서 Swift로 변경, 아래 블로그 예제가 꽤 괜찮아 보인다.
https://blog.pusher.com/building-an-ar-app-with-arkit-and-scenekit/

**Comment by hyunjun529** [comment]
이건 뭐지... 뭔가 비슷한걸 한거 같은데
https://github.com/gao0122/ARKit-Example-by-Apple/blob/master/ARKitExample/ViewController.swift

**Comment by hyunjun529** [comment]
3D UI
https://developer.apple.com/documentation/arkit/handling_3d_interaction_and_ui_controls_in_augmented_reality

**Comment by hyunjun529** [comment]
우리가 표현하던 앵커는 ARAnchor가 아니라 ARSCNView에서 사용하는 앵커였다.

Because ARKit automatically matches SceneKit space to the real world, placing a virtual object such that it appears to maintain a real-world position requires only setting that object's SceneKit position appropriately. (See Providing 3D Virtual Content with SceneKit.)
ARKit은 자동으로 SceneKit 공간을 실제 세계와 일치시키고 실제 위치를 유지하는 것처럼 보이는 가상 객체를 배치하면 해당 객체의 SceneKit 위치만 적절하게 설정하면 된다.

You don't necessarily need to use the ARAnchor class to track positions of objects you add to the scene, but by implementing ARSCNViewDelegate methods, you can add SceneKit content to any anchors that are automatically detected by ARKit.
ARAnchor 클래스를 사용하여 객체의 위치를 추적할 필요는 없다. ARSCNViewDelegate 메소드를 구현하면 ARKit의 앵커에 탐지되는 SceneKit의 앵커를 사용하는 컨텐츠를 만들 수 있다.

https://developer.apple.com/documentation/arkit/arscnview

**Comment by hyunjun529** [comment]
ARSCNView ... 생각보다 불편하다

https://blog.pusher.com/building-an-ar-app-with-arkit-and-scenekit/

http://www.opengl-tutorial.org/kr/beginners-tutorials/tutorial-3-matrices/#평행이동-행렬

**Comment by hyunjun529** [comment]
기능 테스트 완료.

**Comment by ghost** [comment]
최종 보고서  ver.1입니다. 확인하시고 코멘트 남겨주세요.
[[종합설계1]최종보고서(5조_허문용) .pdf](https://github.com/CSID-DGU/2017-2-CECD-Tres-5/files/1545683/1.5._.pdf)

**Comment by ghost** [comment]
[[종합설계]최종발표ver1.pdf](https://github.com/CSID-DGU/2017-2-CECD-Tres-5/files/1545971/ver1.pdf)
[[종합설계]최종발표ver1.pptx](https://github.com/CSID-DGU/2017-2-CECD-Tres-5/files/1545972/ver1.pptx)

최종 발표자료 초안입니다. 내일 오전 11시 59분까지 수정가능합니다. 연락주세요.
